apiVersion: v1
kind: ReplicationController
metadata:
        name: mavenapprc
spec:
        replicas: 2
        selector:
                app: maven
        template:
                metadata:
                        name: mavenapp
                        labels:
                                app: maven
                spec:
                    containers:
                    - name: mavencontainer
                      image: "yogi1995/scotiademo"
                      ports:
                          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
        name: mavenappsvc
        namespace: default
spec:
        type: NodePort
        selector:
                app: maven
        ports:
                - port: 80
                  targetPort: 8080
                  nodePort: 32162
